sonar.projectKey=AlanCS7_fc-sonarcloud-go
sonar.organization=alancs7

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
